import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import type { Post } from "@prisma/client";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import toast from "react-hot-toast";
import { LoadingPage, LoadingSpinner } from "~/components/loading";

import { api, type RouterOutputs } from "~/utils/api";

const CreatePostWizard = () => {
  const { user, isSignedIn } = useUser();

  const [input, setInput] = useState("");

  const utils = api.useUtils();

  const postMutation = api.post.create.useMutation({
    onSuccess: () => {
      setInput(""); 
      utils.post.getLatest.invalidate(); 
    },
    onError: (e) => {
      setInput("");
      const errorMessage = e.data?.zodError?.fieldErrors.content;
      if (errorMessage && errorMessage[0]) {
        toast.error(errorMessage[0]);
      } else {
        toast.error("Failed to post! Please try again later.")
      }
    }
  });


  if (!isSignedIn || !user) return null;

  return (
    <div className="flex w-full gap-3">
      <Image 
        src={user.imageUrl} 
        alt="Profile Image"
        className="h-14 w-14 rounded-full"
        width={56} 
        height={56}
        />
      <input 
        placeholder="Type some emojis!" 
        className="grow bg-transparent outline-0"
        type="text"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={(e) => {
          if (e.key == "Enter") {
            e.preventDefault();
            if (input !== "") {
              postMutation.mutate({ content: input })
            }
          }
        }}
        disabled={postMutation.isPending}
      />
      {input !== "" && (
        <button 
          onClick={() => postMutation.mutate({ content: input })}
          disabled={postMutation.isPending}
        >
          Post
        </button>
      )}
      {postMutation.isPending && (
        <div className="flex items-center justify-center">
          <LoadingSpinner size={20}/>
        </div>)}
    </div>
    );

  
}


type PostWithUser =  RouterOutputs["post"]["getLatest"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props
  return (
    <div key={post.id} className="flex border-b gap-3 border-slate-400 p-4">
      <Image src={author.imageUrl} className="h-14 w-14 rounded-full" alt="`@${author.username} `" width={56} height={56}/>
      <div className="flex flex-col">
        <div className="flex text-slate-300">
          <Link href={`/@${author.username}`}><span>{`@${author.username}`}</span></Link>
        </div>
        <Link href={'/post/${post.id}'}><span className="text-2xl">{post.content}</span></Link>
      </div>
    </div>
  )
}

const Feed = () => {
  const { data, isLoading: postsLoading} = api.post.getLatest.useQuery();

  if (postsLoading) return <LoadingPage/>;

  if (!data) return <div>Something went wrong!</div>

  return (
    <div className="flex flex-col">
      {data.map((fullPost: PostWithUser) => 
        <PostView {...fullPost} key={fullPost.post.id} />
      )}
    </div>
  );

}

export default function Home() {
  const { isLoaded: userLoaded, isSignedIn} = useUser();

  // Start fetching asap
  api.post.getLatest.useQuery();

  if (!userLoaded) return <div/>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full h-screen justify-center">
        <div className="h_full w-full border-x md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {isSignedIn && <CreatePostWizard />}
          </div>
          <Feed/>
        </div>
      </main>
    </>
  );
}
